/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include "Calculadora.h"
#include <stdio.h>

void realizar_operacion(char *host, int a, int b) {
    CLIENT *clnt;
    int *result;
    dupla_int args;
    args.a = a;
    args.b = b;

    clnt = clnt_create(host, CALCULADORA_PROG, CALCULADORA_VERS, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror(host);
        exit(1);
    }

    result = suma_1(&args, clnt);
    printf("Suma: %d\n", *result);

    result = resta_1(&args, clnt);
    printf("Resta: %d\n", *result);

    result = multiplica_1(&args, clnt);
    printf("Multiplicación: %d\n", *result);

    result = divide_1(&args, clnt);
    printf("División: %d\n", *result);

    clnt_destroy(clnt);
}

int main(int argc, char *argv[]) {
    if (argc != 4) {
        printf("Uso: %s servidor num1 num2\n", argv[0]);
        exit(1);
    }

    realizar_operacion(argv[1], atoi(argv[2]), atoi(argv[3]));
}
